/*

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT EMPNO, ENAME, SAL, COMM FROM EMP;

SELECT EMPNO, ENAME, SAL, COALESCE(COMM,0) AS Commission FROM EMP;


SELECT ENAME, JOB FROM EMP WHERE DEPTNO IN (10, 20);

SELECT ENAME, JOB FROM EMP 
WHERE ENAME LIKE "%I%" or JOB LIKE "%ER"
;

SELECT ENAME, JOB FROM EMP
WHERE DEPTNO IN (10, 20) AND ENAME LIKE "%I%"
;

SELECT ENAME, JOB FROM EMP
WHERE DEPTNO IN (10, 20) AND JOB LIKE "%ER"
;

SELECT ENAME, JOB FROM EMP
WHERE DEPTNO IN (10, 20) AND ENAME LIKE "%I%" AND JOB LIKE "%ER"
;

SELECT ENAME, JOB FROM EMP 
WHERE DEPTNO IN (10, 20) AND (ENAME LIKE "%I%" OR JOB LIKE "%ER")
;
*/
